baseURL = "http://example.org/"
languageCode = "en-us"
title = "IDA | In-Depth Architecture"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "IDA"
  description = "In-Depth Architecture"